# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in twitter.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 0.80"

gem 'httparty', '~> 0.13.7'

gem 'simple_oauth', '~> 0.3.1'

